import 'package:drift/drift.dart';
import 'package:not_to_do_list/data/database/app_database.dart';
import 'package:not_to_do_list/data/database/tables/daily_checkins_table.dart';

part 'daily_checkins_dao.g.dart';

/// Drift DAO for the [DailyCheckins] table — typed CRUD for Phase 5 daily
/// self-report check-ins (STRK-03).
///
/// Hand-written (no @riverpod codegen). The `_$DailyCheckinsDaoMixin` is
/// generated by drift_dev via `dart run build_runner build`.
///
/// Unique key `(entryId, day)` drives the upsert target — NOT the primary key
/// (Drift Pitfall #5: plain `insertOnConflictUpdate` only targets the PK and
/// would throw a UNIQUE constraint on the secondary unique key).
@DriftAccessor(tables: [DailyCheckins])
class DailyCheckinsDao extends DatabaseAccessor<AppDatabase>
    with _$DailyCheckinsDaoMixin {
  DailyCheckinsDao(super.attachedDatabase);

  /// Upsert one check-in for (entryId, day). Idempotent — a second call with
  /// the same (entryId, day) overwrites the existing row (STRK-03). `avoided`
  /// and `answeredAt` reflect the most recent submission.
  ///
  /// Uses DoUpdate with explicit target `(entryId, day)` — NOT the primary key.
  Future<int> upsert({
    required int entryId,
    required DateTime day,
    required bool avoided,
    required DateTime answeredAt,
  }) {
    final companion = DailyCheckinsCompanion.insert(
      entryId: entryId,
      day: day,
      avoided: avoided,
      answeredAt: answeredAt,
    );
    return into(dailyCheckins).insert(
      companion,
      onConflict: DoUpdate(
        (_) => companion,
        target: [dailyCheckins.entryId, dailyCheckins.day],
      ),
    );
  }

  /// Returns the check-in row for (entryId, day), or null when no row exists.
  Future<DailyCheckin?> getFor(int entryId, DateTime day) {
    return (select(dailyCheckins)
          ..where(
            (t) => t.entryId.equals(entryId) & t.day.equals(day),
          ))
        .getSingleOrNull();
  }
}
