import 'package:drift/drift.dart';
import 'package:not_to_do_list/data/database/app_database.dart';
import 'package:not_to_do_list/data/database/tables/daily_usage_summary_table.dart';

part 'daily_usage_summary_dao.g.dart';

/// Drift DAO for the [DailyUsageSummary] table — typed CRUD over Phase 1's
/// pre-aggregated daily totals. Phase 3 surface is intentionally minimal:
/// upsertDay (idempotent — D-14), getTodayFor (5-min staleness check — D-12),
/// watchRange (DASH-02/03/04 dashboard list).
///
/// Hand-written (no @riverpod codegen). The `_$DailyUsageSummaryDaoMixin`
/// is generated by drift_dev via `dart run build_runner build`.
@DriftAccessor(tables: [DailyUsageSummary])
class DailyUsageSummaryDao extends DatabaseAccessor<AppDatabase>
    with _$DailyUsageSummaryDaoMixin {
  DailyUsageSummaryDao(super.attachedDatabase);

  /// Upsert one day's row for one package. Idempotent — re-running mid-day
  /// overwrites today's row with fresh totals (D-14, D-12). Backed by the
  /// unique key {packageName, day} on the daily_usage_summary table.
  ///
  /// Uses DoUpdate with an explicit target on `(packageName, day)` — NOT the
  /// primary key. Drift's plain `insertOnConflictUpdate` only targets the
  /// primary key by default, which would throw a UNIQUE constraint on the
  /// secondary uniqueKey (Pitfall #5).
  Future<void> upsertDay({
    required String packageName,
    required DateTime day,
    required int foregroundSeconds,
    required int launchCount,
    required DateTime aggregatedAt,
  }) {
    final companion = DailyUsageSummaryCompanion.insert(
      packageName: packageName,
      day: day,
      foregroundSeconds: foregroundSeconds,
      launchCount: Value(launchCount),
      aggregatedAt: aggregatedAt,
    );
    return into(dailyUsageSummary).insert(
      companion,
      onConflict: DoUpdate(
        (_) => companion,
        target: [dailyUsageSummary.packageName, dailyUsageSummary.day],
      ),
    );
  }

  /// Today's row for the staleness check (D-12). Returns null when no row
  /// exists yet (first-run for that package, or never observed).
  Future<DailyUsageSummaryData?> getTodayFor(
    String packageName,
    DateTime localMidnight,
  ) {
    return (select(dailyUsageSummary)
          ..where(
            (t) =>
                t.packageName.equals(packageName) &
                t.day.equals(localMidnight),
          ))
        .getSingleOrNull();
  }

  /// Reactive stream over [startDay, endDay] (inclusive on both ends — Drift's
  /// isBetweenValues is inclusive). Emits on every transaction commit
  /// affecting daily_usage_summary. Used by:
  /// - dashboardRowsProvider (DASH-02 day; DASH-03 week — last 7d; DASH-04
  ///   month — last 30d, table-only path)
  /// - usageRepositoryProvider in repo tests
  Stream<List<DailyUsageSummaryData>> watchRange(
    DateTime startDay,
    DateTime endDay,
  ) {
    return (select(dailyUsageSummary)
          ..where((t) => t.day.isBetweenValues(startDay, endDay))
          ..orderBy([(t) => OrderingTerm.desc(t.day)]))
        .watch();
  }
}
