import 'package:drift/drift.dart';
import 'package:not_to_do_list/data/database/app_database.dart';
import 'package:not_to_do_list/data/database/tables/daily_streak_table.dart';

part 'daily_streak_dao.g.dart';

/// Drift DAO for the [DailyStreak] table — typed CRUD + streak aggregation
/// for Phase 5 (STRK-01, STRK-05, STRK-07, D-16).
///
/// Hand-written (no @riverpod codegen). The `_$DailyStreakDaoMixin` is
/// generated by drift_dev via `dart run build_runner build`.
///
/// Unique key `(entryId, day)` drives the upsert target — NOT the primary key
/// (Drift Pitfall #5: plain `insertOnConflictUpdate` only targets the PK).
@DriftAccessor(tables: [DailyStreak])
class DailyStreakDao extends DatabaseAccessor<AppDatabase>
    with _$DailyStreakDaoMixin {
  DailyStreakDao(super.attachedDatabase);

  /// Upsert one streak row for (entryId, day). Idempotent — a second call with
  /// the same (entryId, day) overwrites all fields (STRK-01).
  ///
  /// Status int: 0=success, 1=broken, 2=incomplete-data, 3=pending.
  /// Source int: 0=system-confirmed, 1=self-reported-only.
  Future<int> upsert({
    required int entryId,
    required DateTime day,
    required int status,
    required int source,
    required int usageMinutesObserved,
    required DateTime evaluatedAt,
  }) {
    final companion = DailyStreakCompanion.insert(
      entryId: entryId,
      day: day,
      status: status,
      source: source,
      usageMinutesObserved: Value(usageMinutesObserved),
      evaluatedAt: evaluatedAt,
    );
    return into(dailyStreak).insert(
      companion,
      onConflict: DoUpdate(
        (_) => companion,
        target: [dailyStreak.entryId, dailyStreak.day],
      ),
    );
  }

  /// Insert a streak row only when no row exists for (entryId, day). When a
  /// row is already present, returns its id without overwriting. Used by
  /// StreakRolloverService to seed today's `status=3 pending` row (STRK-05)
  /// without clobbering an already-evaluated row.
  ///
  /// Implementation uses select-then-insert (NOT Drift onConflict) because
  /// the required semantics are "do NOT overwrite existing rows" — the opposite
  /// of upsert.
  Future<int> upsertIfAbsent({
    required int entryId,
    required DateTime day,
    required int status,
    required int source,
    required int usageMinutesObserved,
    required DateTime evaluatedAt,
  }) async {
    final existing = await getFor(entryId, day);
    if (existing != null) return existing.id;
    final companion = DailyStreakCompanion.insert(
      entryId: entryId,
      day: day,
      status: status,
      source: source,
      usageMinutesObserved: Value(usageMinutesObserved),
      evaluatedAt: evaluatedAt,
    );
    return into(dailyStreak).insert(companion);
  }

  /// Returns the streak row for (entryId, day), or null when no row exists.
  Future<DailyStreakData?> getFor(int entryId, DateTime day) {
    return (select(dailyStreak)
          ..where(
            (t) => t.entryId.equals(entryId) & t.day.equals(day),
          ))
        .getSingleOrNull();
  }

  /// Returns the number of consecutive days immediately preceding today where
  /// status=0 (success). Today's pending row (status=3) is excluded. Returns 0
  /// when there are no successful days or when the most recent success row is
  /// not from yesterday (streak is broken/gap).
  ///
  /// Algorithm: fetch all status=0 rows for the entry ordered by day desc;
  /// walk backwards from the most recent row counting consecutive days where
  /// each row's day is exactly 1 day before the previous. Stop at first gap.
  Future<int> getCurrentStreakFor(int entryId) async {
    final rows = await (select(dailyStreak)
          ..where(
            (t) => t.entryId.equals(entryId) & t.status.equals(0),
          )
          ..orderBy([(t) => OrderingTerm.desc(t.day)]))
        .get();

    if (rows.isEmpty) return 0;

    // The streak must include yesterday to be "current". If the most recent
    // success row is older than yesterday, the streak is not current.
    // Use local-time midnight throughout so Drift's local-time read-back is
    // consistently compared (Drift NativeDatabase returns local DateTime).
    final today = DateTime.now();
    final todayMidnight =
        DateTime(today.year, today.month, today.day);
    final yesterday = todayMidnight.subtract(const Duration(days: 1));

    // Normalize row.day to local midnight (strip sub-day components)
    DateTime toLocalMidnight(DateTime d) =>
        DateTime(d.year, d.month, d.day);

    final firstDayMidnight = toLocalMidnight(rows.first.day);

    if (firstDayMidnight.isBefore(yesterday)) return 0;

    // Walk consecutive days backwards
    int count = 0;
    DateTime? expectedDay;
    for (final row in rows) {
      final rowDayMidnight = toLocalMidnight(row.day);
      if (expectedDay == null) {
        count = 1;
        expectedDay = rowDayMidnight.subtract(const Duration(days: 1));
      } else if (rowDayMidnight == expectedDay) {
        count++;
        expectedDay = rowDayMidnight.subtract(const Duration(days: 1));
      } else {
        break;
      }
    }
    return count;
  }

  /// Returns the longest consecutive run of status=0 (success) days across the
  /// full history for the entry. Returns 0 when no success rows exist (STRK-07).
  ///
  /// Algorithm: fetch all status=0 rows ordered by day asc; walk forward
  /// counting consecutive runs where each row's day is exactly 1 day after
  /// the previous; track the maximum run length.
  Future<int> getLongestStreakFor(int entryId) async {
    final rows = await (select(dailyStreak)
          ..where(
            (t) => t.entryId.equals(entryId) & t.status.equals(0),
          )
          ..orderBy([(t) => OrderingTerm.asc(t.day)]))
        .get();

    if (rows.isEmpty) return 0;

    // Normalize to local midnight for consistent day comparison
    DateTime toLocalMidnight(DateTime d) =>
        DateTime(d.year, d.month, d.day);

    var maxRun = 1;
    var currentRun = 1;
    for (var i = 1; i < rows.length; i++) {
      final prevMidnight = toLocalMidnight(rows[i - 1].day);
      final currMidnight = toLocalMidnight(rows[i].day);
      final expectedNext = prevMidnight.add(const Duration(days: 1));
      if (currMidnight == expectedNext) {
        currentRun++;
        if (currentRun > maxRun) maxRun = currentRun;
      } else {
        currentRun = 1;
      }
    }
    return maxRun;
  }

  /// Reactive stream of streak rows for the entry in the last [days] calendar
  /// days, ordered by day ascending (D-16 history). Emits on every write
  /// within the window. Default window is 30 days.
  ///
  /// The cutoff is inclusive: rows where day >= (today - (days-1) days).
  Stream<List<DailyStreakData>> watchHistoryFor(
    int entryId, {
    int days = 30,
  }) {
    final today = DateTime.now();
    final cutoff = DateTime(today.year, today.month, today.day)
        .subtract(Duration(days: days - 1));
    return (select(dailyStreak)
          ..where(
            (t) =>
                t.entryId.equals(entryId) &
                t.day.isBiggerOrEqualValue(cutoff),
          )
          ..orderBy([(t) => OrderingTerm.asc(t.day)]))
        .watch();
  }

  /// Convenience all-time stream ordered by day descending. Used by badge
  /// providers or other consumers that need the full entry history.
  Stream<List<DailyStreakData>> watchForEntry(int entryId) {
    return (select(dailyStreak)
          ..where((t) => t.entryId.equals(entryId))
          ..orderBy([(t) => OrderingTerm.desc(t.day)]))
        .watch();
  }
}
