// Plan 02-02 fills in the assertions originally stubbed in Plan 02-01.
//
// Verifies the Drift v1 → v2 upgrade against the v1 schema fixture captured
// in drift_schemas/drift_schema_v1.json (Plan 02-01) and the helpers
// generated by `dart run drift_dev schema generate` into
// test/generated_migrations/.

// `isNull` is exported by both `package:drift/drift.dart` (column-side
// matcher) and `package:matcher` (test matcher used in expect). We use the
// matcher form here, so hide the drift symbol to disambiguate.
import 'package:drift/drift.dart' hide isNull;
import 'package:drift/native.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:not_to_do_list/data/database/app_database.dart';

import '../../generated_migrations/schema.dart';
import '../../generated_migrations/schema_v1.dart' as v1;

void main() {
  group('AppDatabase v1 → v2 migration (LIST-08, LIST-09)', () {
    late SchemaVerifier verifier;

    setUpAll(() {
      verifier = SchemaVerifier(GeneratedHelper());
    });

    test('schemaVersion is 2', () async {
      final db = AppDatabase(NativeDatabase.memory());
      addTearDown(db.close);
      expect(db.schemaVersion, 2);
    });

    test(
      'v1 → v2: existing v1 row gets block_mode=soft and null schedules',
      () async {
        // Open at v1 using the generated helper, insert a Phase-1-shape row,
        // then reopen the same backing DB through AppDatabase — Drift fires
        // onUpgrade(1, 2) which adds the four Phase 2 columns.
        final schema = await verifier.schemaAt(1);

        final v1Db = v1.DatabaseAtV1(schema.newConnection());
        final createdAtSec =
            DateTime.utc(2026, 4, 27).millisecondsSinceEpoch ~/ 1000;
        await v1Db.customStatement(
          'INSERT INTO block_list '
          '(kind, package_name, display_name, reason_note, '
          'streak_break_threshold_minutes, created_at, updated_at) '
          'VALUES (?, ?, ?, ?, ?, ?, ?)',
          <Object?>[
            0,
            'com.instagram.android',
            'Instagram',
            'Doomscrolling',
            5,
            createdAtSec,
            createdAtSec,
          ],
        );
        await v1Db.close();

        // Reopen the same backing DB via the new schema; Drift triggers
        // onUpgrade and applies the four addColumn statements.
        final db = AppDatabase(schema.newConnection());
        addTearDown(db.close);

        final rows = await db.select(db.blockList).get();
        expect(rows, hasLength(1));
        expect(rows[0].displayName, 'Instagram');
        expect(rows[0].packageName, 'com.instagram.android');
        expect(rows[0].blockMode, 'soft');
        expect(rows[0].scheduleStartMinutes, isNull);
        expect(rows[0].scheduleEndMinutes, isNull);
        expect(rows[0].scheduleWeekdayMask, isNull);
      },
    );

    test('v2 createAll round-trip preserves schedule columns', () async {
      final db = AppDatabase(NativeDatabase.memory());
      addTearDown(db.close);
      await db.into(db.blockList).insert(
            BlockListCompanion.insert(
              kind: 0,
              packageName: const Value('com.tiktok'),
              displayName: 'TikTok',
              reasonNote: const Value(''),
              createdAt: DateTime.utc(2026, 5, 5),
              updatedAt: DateTime.utc(2026, 5, 5),
              blockMode: const Value('hard'),
              scheduleStartMinutes: const Value(1320), // 22:00
              scheduleEndMinutes: const Value(360), // 06:00 (cross-midnight)
              scheduleWeekdayMask: const Value(0x1F), // Mon–Fri = 0b00011111
            ),
          );
      final rows = await db.select(db.blockList).get();
      expect(rows.single.blockMode, 'hard');
      expect(rows.single.scheduleStartMinutes, 1320);
      expect(rows.single.scheduleEndMinutes, 360);
      expect(rows.single.scheduleWeekdayMask, 0x1F);
    });
  });
}
