// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nottodo.not_to_do_list.platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AppPickerApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is AppPickerApiError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class AppPickerApiError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class InstalledApp (
  val packageName: String,
  val displayName: String,
  val isSystemApp: Boolean,
  val hasLauncherIntent: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InstalledApp {
      val packageName = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val isSystemApp = pigeonVar_list[2] as Boolean
      val hasLauncherIntent = pigeonVar_list[3] as Boolean
      return InstalledApp(packageName, displayName, isSystemApp, hasLauncherIntent)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      displayName,
      isSystemApp,
      hasLauncherIntent,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as InstalledApp
    return AppPickerApiPigeonUtils.deepEquals(this.packageName, other.packageName) && AppPickerApiPigeonUtils.deepEquals(this.displayName, other.displayName) && AppPickerApiPigeonUtils.deepEquals(this.isSystemApp, other.isSystemApp) && AppPickerApiPigeonUtils.deepEquals(this.hasLauncherIntent, other.hasLauncherIntent)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AppPickerApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + AppPickerApiPigeonUtils.deepHash(this.displayName)
    result = 31 * result + AppPickerApiPigeonUtils.deepHash(this.isSystemApp)
    result = 31 * result + AppPickerApiPigeonUtils.deepHash(this.hasLauncherIntent)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RecentApp (
  val packageName: String,
  val totalForegroundSeconds: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecentApp {
      val packageName = pigeonVar_list[0] as String
      val totalForegroundSeconds = pigeonVar_list[1] as Long
      return RecentApp(packageName, totalForegroundSeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      totalForegroundSeconds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RecentApp
    return AppPickerApiPigeonUtils.deepEquals(this.packageName, other.packageName) && AppPickerApiPigeonUtils.deepEquals(this.totalForegroundSeconds, other.totalForegroundSeconds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AppPickerApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + AppPickerApiPigeonUtils.deepHash(this.totalForegroundSeconds)
    return result
  }
}
private open class AppPickerApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstalledApp.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecentApp.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is InstalledApp -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RecentApp -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AppPickerApi {
  /**
   * Returns ALL installed apps; Dart-side filter on `isSystemApp && !hasLauncherIntent`
   * implements the default "hide non-launchable system apps" view (T-2-01 mitigation).
   * Visibility scope is governed by Phase 1's <queries> + LAUNCHER manifest entry —
   * no QUERY_ALL_PACKAGES permission is requested.
   */
  fun listInstalledApps(callback: (Result<List<InstalledApp>>) -> Unit)
  /**
   * Returns top apps by foreground seconds in the trailing window.
   * Caller is responsible for first checking that Usage Access is granted via
   * PermissionStatusApi.isUsageAccessGranted() — this method returns an empty list
   * (NOT throw) if not granted, to keep the Dart code branch-light.
   */
  fun recentlyUsedApps(daysBack: Long, callback: (Result<List<RecentApp>>) -> Unit)
  /**
   * Returns null if the package is not installed or the icon couldn't be encoded.
   * Encoded as PNG bytes. Decoded on the Dart side via Image.memory.
   */
  fun getApplicationIconPng(packageName: String, callback: (Result<ByteArray?>) -> Unit)

  companion object {
    /** The codec used by AppPickerApi. */
    val codec: MessageCodec<Any?> by lazy {
      AppPickerApiPigeonCodec()
    }
    /** Sets up an instance of `AppPickerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AppPickerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.AppPickerApi.listInstalledApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.listInstalledApps{ result: Result<List<InstalledApp>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AppPickerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AppPickerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.AppPickerApi.recentlyUsedApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val daysBackArg = args[0] as Long
            api.recentlyUsedApps(daysBackArg) { result: Result<List<RecentApp>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AppPickerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AppPickerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.AppPickerApi.getApplicationIconPng$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.getApplicationIconPng(packageNameArg) { result: Result<ByteArray?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AppPickerApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AppPickerApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
