// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nottodo.not_to_do_list.platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BlocklistBroadcastApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is BlocklistBroadcastApiError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class BlocklistBroadcastApiError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class BlockListEntrySnapshot (
  val entryId: Long,
  val packageName: String,
  val blockMode: String,
  val scheduleStartMinutes: Long? = null,
  val scheduleEndMinutes: Long? = null,
  val scheduleWeekdayMask: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BlockListEntrySnapshot {
      val entryId = pigeonVar_list[0] as Long
      val packageName = pigeonVar_list[1] as String
      val blockMode = pigeonVar_list[2] as String
      val scheduleStartMinutes = pigeonVar_list[3] as Long?
      val scheduleEndMinutes = pigeonVar_list[4] as Long?
      val scheduleWeekdayMask = pigeonVar_list[5] as Long?
      return BlockListEntrySnapshot(entryId, packageName, blockMode, scheduleStartMinutes, scheduleEndMinutes, scheduleWeekdayMask)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      entryId,
      packageName,
      blockMode,
      scheduleStartMinutes,
      scheduleEndMinutes,
      scheduleWeekdayMask,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BlockListEntrySnapshot
    return BlocklistBroadcastApiPigeonUtils.deepEquals(this.entryId, other.entryId) && BlocklistBroadcastApiPigeonUtils.deepEquals(this.packageName, other.packageName) && BlocklistBroadcastApiPigeonUtils.deepEquals(this.blockMode, other.blockMode) && BlocklistBroadcastApiPigeonUtils.deepEquals(this.scheduleStartMinutes, other.scheduleStartMinutes) && BlocklistBroadcastApiPigeonUtils.deepEquals(this.scheduleEndMinutes, other.scheduleEndMinutes) && BlocklistBroadcastApiPigeonUtils.deepEquals(this.scheduleWeekdayMask, other.scheduleWeekdayMask)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + BlocklistBroadcastApiPigeonUtils.deepHash(this.entryId)
    result = 31 * result + BlocklistBroadcastApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + BlocklistBroadcastApiPigeonUtils.deepHash(this.blockMode)
    result = 31 * result + BlocklistBroadcastApiPigeonUtils.deepHash(this.scheduleStartMinutes)
    result = 31 * result + BlocklistBroadcastApiPigeonUtils.deepHash(this.scheduleEndMinutes)
    result = 31 * result + BlocklistBroadcastApiPigeonUtils.deepHash(this.scheduleWeekdayMask)
    return result
  }
}
private open class BlocklistBroadcastApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BlockListEntrySnapshot.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BlockListEntrySnapshot -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BlocklistBroadcastApi {
  /**
   * Fire-and-forget Dart→Kotlin call. Kotlin side translates to a
   * LocalBroadcast with action `com.nottodo.not_to_do_list.ACTION_BLOCKLIST_UPDATED`
   * carrying the snapshot list as JSON extra.
   *
   * Habit entries (no packageName) MUST be filtered out by the caller —
   * the service only cares about app entries.
   *
   * PLAY-02 / D-10: this channel is the SOLE seam between Dart-owned
   * BlockListRepository and the native AccessibilityService's in-memory
   * Map<String, ScheduleSlice>. Service NEVER reads SQLite (Pattern 1).
   */
  fun publishBlockList(entries: List<BlockListEntrySnapshot>)

  companion object {
    /** The codec used by BlocklistBroadcastApi. */
    val codec: MessageCodec<Any?> by lazy {
      BlocklistBroadcastApiPigeonCodec()
    }
    /** Sets up an instance of `BlocklistBroadcastApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BlocklistBroadcastApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.BlocklistBroadcastApi.publishBlockList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entriesArg = args[0] as List<BlockListEntrySnapshot>
            val wrapped: List<Any?> = try {
              api.publishBlockList(entriesArg)
              listOf(null)
            } catch (exception: Throwable) {
              BlocklistBroadcastApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
