// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nottodo.not_to_do_list.platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PermissionStatusApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is PermissionStatusApiError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class PermissionStatusApiError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class PermissionStatusApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PermissionStatusApi {
  /** True iff AppOpsManager.OPSTR_GET_USAGE_STATS == MODE_ALLOWED for our package. */
  fun isUsageAccessGranted(callback: (Result<Boolean>) -> Unit)
  /**
   * True iff our specific accessibility service appears in
   * AccessibilityManager.getEnabledAccessibilityServiceList(). Bundled here
   * (in addition to AccessibilityApi.isServiceEnabled() from Phase 1) so the
   * resume-detection round-trip can fetch all four checks in one call.
   */
  fun isAccessibilityServiceEnabled(callback: (Result<Boolean>) -> Unit)
  /** True iff PowerManager.isIgnoringBatteryOptimizations(packageName) is true. */
  fun isIgnoringBatteryOptimizations(callback: (Result<Boolean>) -> Unit)
  /** Build.FINGERPRINT — used to detect OS upgrade between launches (ONBD-07). */
  fun currentBuildFingerprint(callback: (Result<String>) -> Unit)
  /**
   * Build.MANUFACTURER (lowercased on the Kotlin side) — used to look up
   * per-OEM fallback ComponentNames + dontkillmyapp.com slug (REL-03).
   */
  fun currentManufacturer(callback: (Result<String>) -> Unit)
  /**
   * Launches Settings.ACTION_USAGE_ACCESS_SETTINGS, with resolveActivity()
   * guard + ACTION_APPLICATION_DETAILS_SETTINGS fallback (T-2-02 mitigation).
   */
  fun openUsageAccessSettings(callback: (Result<Unit>) -> Unit)
  /**
   * Launches Settings.ACTION_ACCESSIBILITY_SETTINGS, with resolveActivity()
   * guard + ACTION_APPLICATION_DETAILS_SETTINGS fallback (T-2-02 mitigation).
   */
  fun openAccessibilitySettings(callback: (Result<Unit>) -> Unit)
  /**
   * Launches Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS with
   * `package:` data Uri, with resolveActivity() guard + ACTION_IGNORE_*
   * fallback (T-2-02 mitigation).
   */
  fun openBatteryOptSettings(callback: (Result<Unit>) -> Unit)
  /** POST_NOTIFICATIONS runtime permission status (Android 13+) — NOTF-06. */
  fun isPostNotificationsGranted(callback: (Result<Boolean>) -> Unit)
  /** Three-state for D-12 banner UX — grantable/rationale/permanently_denied. */
  fun postNotificationsRationaleState(callback: (Result<String>) -> Unit)
  /**
   * Launches the runtime POST_NOTIFICATIONS dialog (NOTF-06 earned prompt).
   *
   * SEMANTIC NOTE — non-blocking return value:
   * This method returns the PRE-dialog granted state, NOT the post-dialog state.
   * The Android runtime permission dialog is delivered to MainActivity.onRequestPermissionsResult
   * asynchronously; this Pigeon method cannot block on that callback without holding the Flutter
   * engine thread. The caller (Plan 05-08 PostNotificationsEarnedStep) re-polls
   * isPostNotificationsGranted() on AppLifecycleState.resumed via WidgetsBindingObserver to observe
   * the user's grant decision. See T-05-16 threat entry for the full lifecycle contract.
   */
  fun requestPostNotifications(callback: (Result<Boolean>) -> Unit)
  /** Boot-monotonic clock for clock-tamper detection — STRK-06. */
  fun bootMonotonicNanos(callback: (Result<Long>) -> Unit)
  /** ACTION_APP_NOTIFICATION_SETTINGS deep-link with resolveActivity guard + applicationDetails fallback (T-2-02 mitigation). */
  fun openAppNotificationSettings(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by PermissionStatusApi. */
    val codec: MessageCodec<Any?> by lazy {
      PermissionStatusApiPigeonCodec()
    }
    /** Sets up an instance of `PermissionStatusApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PermissionStatusApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.isUsageAccessGranted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isUsageAccessGranted{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.isAccessibilityServiceEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isAccessibilityServiceEnabled{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.isIgnoringBatteryOptimizations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isIgnoringBatteryOptimizations{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.currentBuildFingerprint$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.currentBuildFingerprint{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.currentManufacturer$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.currentManufacturer{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.openUsageAccessSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openUsageAccessSettings{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.openAccessibilitySettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openAccessibilitySettings{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.openBatteryOptSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openBatteryOptSettings{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.isPostNotificationsGranted$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isPostNotificationsGranted{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.postNotificationsRationaleState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.postNotificationsRationaleState{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.requestPostNotifications$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestPostNotifications{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.bootMonotonicNanos$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.bootMonotonicNanos{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.not_to_do_list.PermissionStatusApi.openAppNotificationSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.openAppNotificationSettings{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(PermissionStatusApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(PermissionStatusApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
